extends RefCounted
class_name ChunkManager

## ChunkManager - continuous chunk streaming: loads nearby, unloads distant
## Fixed to ensure continuous popping in/out as player moves

signal chunk_loaded(coord: Vector2i)
signal chunk_unloaded(coord: Vector2i)
signal streaming_updated(stats: Dictionary)

const _ChunkCoord = preload("res://world/streaming/chunk_coord.gd")

var config: WorldConfig
var voxel_model: VoxelWorld
var chunk_renderer: ChunkRenderSystem
var terrain_generator: TerrainGenerator

var player_ref: Node3D = null

var loaded_chunks: Dictionary = {} # Vector2i -> true
var load_queue: Array[Vector2i] = []
var unload_queue: Array[Vector2i] = []

var render_distance: int = 2
var unload_distance: int = 4
var max_loads_per_frame: int = 2
var max_unloads_per_frame: int = 4
var update_interval: float = 0.1

var last_player_chunk: Vector2i = Vector2i(-99999, -99999)
var last_update_time: float = 0.0
var _time_accum: float = 0.0

var total_loads: int = 0
var total_unloads: int = 0
var _initialized: bool = false
var use_async: bool = true # false for headless tests to be deterministic

func setup(p_config: WorldConfig, p_voxel_model: VoxelWorld, p_renderer: ChunkRenderSystem, p_terrain_gen: TerrainGenerator = null):
	config = p_config
	voxel_model = p_voxel_model
	chunk_renderer = p_renderer
	terrain_generator = p_terrain_gen
	if config:
		render_distance = config.render_distance
		unload_distance = config.render_distance + config.unload_padding
		max_loads_per_frame = config.max_chunk_loads_per_frame
		max_unloads_per_frame = config.max_chunk_unloads_per_frame
		update_interval = config.chunk_update_interval
	loaded_chunks.clear()
	load_queue.clear()
	unload_queue.clear()
	last_player_chunk = Vector2i(-99999, -99999)
	_time_accum = 0.0
	_initialized = true
	print("[ChunkManager] Setup render_dist=%d unload_dist=%d max_load=%d max_unload=%d interval=%.2f world=%dx%d chunk=%d" % [
		render_distance, unload_distance, max_loads_per_frame, max_unloads_per_frame, update_interval,
		config.world_size if config else 200, config.world_size if config else 200, config.chunk_size if config else 20
	])

func set_player_ref(p_player: Node3D):
	player_ref = p_player
	if player_ref:
		print("[ChunkManager] Player ref set at %s" % player_ref.global_position)

func set_render_distance(d: int):
	render_distance = clamp(d, 1, 16)
	if config:
		unload_distance = render_distance + config.unload_padding
	else:
		unload_distance = render_distance + 2
	print("[ChunkManager] Render distance set %d unload %d" % [render_distance, unload_distance])

func ensure_terrain_for_chunk(coord: Vector2i):
	if not config or not config.infinite_world:
		return
	if not terrain_generator or not voxel_model:
		return
	var origin_x = coord.x * config.chunk_size
	var origin_z = coord.y * config.chunk_size
	# Fast path: if terrain already cached (kept for reload), skip regeneration – eliminates lag on revisit
	# But ensure trees are also present; height may have been generated via torch path without trees
	if voxel_model.has_method("is_chunk_data_available"):
		if voxel_model.is_chunk_data_available(coord.x, coord.y):
			if voxel_model.has_method("ensure_region_generated"):
				voxel_model.ensure_region_generated(origin_x -1, origin_z -1, config.chunk_size + 2, config.chunk_size + 2)
			# If trees missing for this chunk (e.g., column generated by torch placement), generate them now
			var needs_trees = true
			if voxel_model.has_method("has_trees_in_chunk"):
				needs_trees = not voxel_model.has_trees_in_chunk(coord.x, coord.y)
			if needs_trees and terrain_generator.has_method("generate_trees_for_chunk"):
				var tree_data = terrain_generator.generate_trees_for_chunk(origin_x, origin_z, config.chunk_size, config.chunk_size)
				if voxel_model.has_method("apply_tree_chunk"):
					voxel_model.apply_tree_chunk(tree_data)
			return
	var size = config.chunk_size + 2
	if voxel_model.has_method("ensure_region_generated") and voxel_model.has_method("set_generator_ref"):
		voxel_model.ensure_region_generated(origin_x -1, origin_z -1, size, size)
		if terrain_generator.has_method("generate_trees_for_chunk"):
			var tree_data = terrain_generator.generate_trees_for_chunk(origin_x, origin_z, config.chunk_size, config.chunk_size)
			if voxel_model.has_method("apply_tree_chunk"):
				voxel_model.apply_tree_chunk(tree_data)
		return
	var chunk_data = terrain_generator.generate_chunk_region(origin_x -1, origin_z -1, size, size)
	if voxel_model.has_method("apply_chunk_gen"):
		voxel_model.apply_chunk_gen(chunk_data)
	if terrain_generator.has_method("generate_trees_for_chunk"):
		var tree_data = terrain_generator.generate_trees_for_chunk(origin_x, origin_z, config.chunk_size, config.chunk_size)
		if voxel_model.has_method("apply_tree_chunk"):
			voxel_model.apply_tree_chunk(tree_data)

func world_to_chunk(pos: Vector3) -> Vector2i:
	if config == null:
		return _ChunkCoord.world_to_chunk(pos, 20)
	return _ChunkCoord.world_to_chunk(pos, config.chunk_size)

func compute_desired_chunks(center_chunk: Vector2i) -> Array[Vector2i]:
	if config and config.infinite_world:
		return _ChunkCoord.get_chunks_in_radius_infinite(center_chunk, render_distance)
	if config == null:
		return _ChunkCoord.get_chunks_in_radius(center_chunk, render_distance, 200, 20)
	return _ChunkCoord.get_chunks_in_radius(center_chunk, render_distance, config.world_size, config.chunk_size)

func compute_unload_keep_chunks(center_chunk: Vector2i) -> Array[Vector2i]:
	if config and config.infinite_world:
		return _ChunkCoord.get_chunks_in_radius_infinite(center_chunk, unload_distance)
	if config == null:
		return _ChunkCoord.get_chunks_in_radius(center_chunk, unload_distance, 200, 20)
	return _ChunkCoord.get_chunks_in_radius(center_chunk, unload_distance, config.world_size, config.chunk_size)

func update(player_pos: Vector3, force: bool = false) -> bool:
	if not _initialized:
		return false
	var now = Time.get_ticks_msec() / 1000.0
	var center = world_to_chunk(player_pos)

	var moved = center != last_player_chunk
	var time_elapsed = now - last_update_time

	# Only throttle if player hasn't moved chunk and we have no pending work and interval not elapsed
	if not force and not moved:
		# If we still have queues, don't recompute, just let them drain
		if not load_queue.is_empty() or not unload_queue.is_empty():
			return false
		if time_elapsed < update_interval and _time_accum < update_interval:
			return false

	# If player moved chunk, force recompute regardless of interval
	# (unless we already did very recently and queues still draining? we still want to recompute for new direction)
	if not moved and not force:
		if time_elapsed < update_interval:
			return false

	last_player_chunk = center
	last_update_time = now
	_time_accum = 0.0

	var desired = compute_desired_chunks(center)
	var keep = compute_unload_keep_chunks(center)

	var desired_set: Dictionary = {}
	for c in desired:
		desired_set[c] = true
	var keep_set: Dictionary = {}
	for c in keep:
		keep_set[c] = true

	# Sync loaded_chunks with renderer reality
	if chunk_renderer:
		for k in chunk_renderer.chunk_instances.keys():
			var coord = _ChunkCoord.key_to_chunk(k)
			if coord == Vector2i(-9999, -9999):
				continue
			if not loaded_chunks.has(coord):
				loaded_chunks[coord] = true

	# 1) Cancel pending unloads that are now desired again (player moved back)
	var filtered_unload: Array[Vector2i] = []
	for c in unload_queue:
		if desired_set.has(c) or keep_set.has(c):
			# Desired again -> keep it, don't unload
			continue
		filtered_unload.append(c)
	unload_queue = filtered_unload

	# 2) Prune load_queue: remove entries that are no longer needed (not in desired) and not already loaded
	var filtered_load: Array[Vector2i] = []
	for c in load_queue:
		if not desired_set.has(c):
			continue
		if loaded_chunks.has(c):
			continue
		if chunk_renderer:
			if chunk_renderer.is_chunk_loaded(c.x, c.y):
				loaded_chunks[c] = true
				continue
			if chunk_renderer.is_chunk_pending(c.x, c.y):
				# Still async building, keep waiting, don't re-queue
				filtered_load.append(c)
				continue
		filtered_load.append(c)
	load_queue = filtered_load

	# 3) Build new loads (check async pending to avoid duplicate)
	var new_loads: Array[Vector2i] = []
	for c in desired:
		if loaded_chunks.has(c):
			continue
		if load_queue.has(c):
			continue
		if chunk_renderer:
			if chunk_renderer.is_chunk_loaded(c.x, c.y):
				loaded_chunks[c] = true
				continue
			if chunk_renderer.is_chunk_pending(c.x, c.y):
				continue
		# Queue for loading; terrain generation throttled to process_queues to avoid spike
		new_loads.append(c)

	new_loads = _ChunkCoord.sort_by_distance(new_loads, center)
	for c in new_loads:
		load_queue.append(c)
	# Re-sort whole queue by distance for nearest-first popping
	load_queue = _ChunkCoord.sort_by_distance(load_queue, center)

	# 4) Build new unloads: loaded but outside keep
	var new_unloads: Array[Vector2i] = []
	for k in loaded_chunks.keys():
		var coord: Vector2i = k
		if not keep_set.has(coord):
			if not unload_queue.has(coord) and not new_unloads.has(coord):
				# If it's still in load_queue (not yet loaded), don't add to unload, just remove from load
				if load_queue.has(coord):
					continue
				new_unloads.append(coord)

	# Also any renderer chunk outside keep that we missed
	if chunk_renderer:
		for k in chunk_renderer.chunk_instances.keys():
			var coord = _ChunkCoord.key_to_chunk(k)
			if coord == Vector2i(-9999, -9999):
				continue
			if not keep_set.has(coord):
				if not unload_queue.has(coord) and not new_unloads.has(coord) and loaded_chunks.has(coord):
					if load_queue.has(coord):
						continue
					new_unloads.append(coord)

	for c in new_unloads:
		unload_queue.append(c)

	# Sort unloads farthest first so we unload distant first
	unload_queue.sort_custom(func(a,b): return _ChunkCoord.euclidean_distance(a, center) > _ChunkCoord.euclidean_distance(b, center))

	if new_loads.size() > 0 or new_unloads.size() > 0 or moved:
		print("[ChunkManager] Update center %s moved=%s desired %d keep %d | +%d loads (%d queued) +%d unloads (%d queued) loaded %d" % [
			center, moved, desired.size(), keep.size(), new_loads.size(), load_queue.size(), new_unloads.size(), unload_queue.size(), loaded_chunks.size()
		])
		streaming_updated.emit(get_stats())

	return true

func process_queues(p_max_loads: int = -1, p_max_unloads: int = -1) -> Dictionary:
	if not _initialized or chunk_renderer == null:
		return {"loaded":0, "unloaded":0}
	if p_max_loads == -1:
		p_max_loads = max_loads_per_frame
	if p_max_unloads == -1:
		p_max_unloads = max_unloads_per_frame

	var loaded_now = 0
	var unloaded_now = 0

	# Process loads first - async for seamless if use_async, else immediate for tests
	# Terrain gen is now throttled here to avoid generating 121 chunks at once
	var to_load = min(p_max_loads, load_queue.size())
	for i in range(to_load):
		if load_queue.is_empty():
			break
		var coord = load_queue[0]
		load_queue.remove_at(0)
		if chunk_renderer.is_chunk_loaded(coord.x, coord.y):
			loaded_chunks[coord] = true
			continue
		if chunk_renderer.is_chunk_pending(coord.x, coord.y):
			continue
		# Ensure terrain data exists just before meshing (throttled)
		ensure_terrain_for_chunk(coord)
		if use_async:
			var queued = chunk_renderer.rebuild_async(coord.x, coord.y)
			if queued:
				total_loads += 1
				loaded_now += 1
				chunk_loaded.emit(coord)
			else:
				chunk_renderer.rebuild_immediate(coord.x, coord.y)
				loaded_chunks[coord] = true
				total_loads += 1
				loaded_now += 1
				chunk_loaded.emit(coord)
		else:
			chunk_renderer.rebuild_immediate(coord.x, coord.y)
			loaded_chunks[coord] = true
			total_loads += 1
			loaded_now += 1
			chunk_loaded.emit(coord)

	# Process unloads - frees mesh + torches + terrain cache (no CPU/memory for unloaded)
	var to_unload = min(p_max_unloads, unload_queue.size())
	for i in range(to_unload):
		if unload_queue.is_empty():
			break
		var coord = unload_queue[0]
		unload_queue.remove_at(0)
		# If it became desired again while queued, skip
		# Note: update() should have pruned, but double-check
		if not chunk_renderer.is_chunk_loaded(coord.x, coord.y):
			loaded_chunks.erase(coord)
			if voxel_model and voxel_model.has_method("unload_chunk_terrain"):
				voxel_model.unload_chunk_terrain(coord.x, coord.y)
			continue
		chunk_renderer.unload_chunk(coord.x, coord.y)
		if voxel_model and voxel_model.has_method("unload_chunk_terrain"):
			voxel_model.unload_chunk_terrain(coord.x, coord.y)
		loaded_chunks.erase(coord)
		total_unloads += 1
		unloaded_now += 1
		chunk_unloaded.emit(coord)

	return {"loaded": loaded_now, "unloaded": unloaded_now}

func ensure_chunks_around(pos: Vector3) -> int:
	if not _initialized:
		return 0
	var center = world_to_chunk(pos)
	var desired = compute_desired_chunks(center)
	desired = _ChunkCoord.sort_by_distance(desired, center)
	var count = 0
	for coord in desired:
		if chunk_renderer.is_chunk_loaded(coord.x, coord.y):
			loaded_chunks[coord] = true
			continue
		ensure_terrain_for_chunk(coord)
		chunk_renderer.rebuild_immediate(coord.x, coord.y)
		loaded_chunks[coord] = true
		total_loads += 1
		count += 1
	last_player_chunk = center
	last_update_time = Time.get_ticks_msec() / 1000.0
	_time_accum = 0.0
	load_queue.clear()
	unload_queue.clear()
	print("[ChunkManager] ensure_chunks_around %s loaded %d immediate total %d" % [center, count, loaded_chunks.size()])
	return count

func tick(delta: float, player_pos: Vector3 = Vector3.INF) -> Dictionary:
	_time_accum += delta
	var pos = player_pos
	if pos == Vector3.INF:
		if player_ref and is_instance_valid(player_ref):
			pos = player_ref.global_position
		else:
			# No player, still drain queues continuously
			return process_queues()
	# Always attempt update, update handles throttling internally
	update(pos)
	return process_queues()

func clear():
	loaded_chunks.clear()
	load_queue.clear()
	unload_queue.clear()
	last_player_chunk = Vector2i(-99999, -99999)
	_time_accum = 0.0
	last_update_time = 0.0
	if chunk_renderer:
		chunk_renderer.clear()
	total_loads = 0
	total_unloads = 0
	print("[ChunkManager] Cleared all")

func force_unload_all():
	for coord in loaded_chunks.keys():
		if chunk_renderer.is_chunk_loaded(coord.x, coord.y):
			chunk_renderer.unload_chunk(coord.x, coord.y)
	loaded_chunks.clear()
	load_queue.clear()
	unload_queue.clear()

func get_loaded_count() -> int:
	return loaded_chunks.size()

func is_chunk_loaded(coord: Vector2i) -> bool:
	return loaded_chunks.has(coord)

func get_stats() -> Dictionary:
	return {
		"render_distance": render_distance,
		"unload_distance": unload_distance,
		"loaded": loaded_chunks.size(),
		"load_queue": load_queue.size(),
		"unload_queue": unload_queue.size(),
		"total_loads": total_loads,
		"total_unloads": total_unloads,
		"last_player_chunk": last_player_chunk,
		"max_loads_per_frame": max_loads_per_frame,
		"max_unloads_per_frame": max_unloads_per_frame,
		"interval": update_interval,
	}
