extends SceneTree

const SkeletonBehaviorDefinitionType := preload("res://entities/skeleton/skeleton_behavior_definition.gd")
const SkeletonBrainType := preload("res://entities/skeleton/skeleton_brain.gd")

var _failures: int = 0

func _init() -> void:
	call_deferred(&"_run")

func _expect(condition: bool, message: String) -> void:
	if condition:
		return
	_failures += 1
	push_error("[skeleton_brain] FAIL: %s" % message)

func _make_behavior() -> SkeletonBehaviorDefinition:
	var behavior := SkeletonBehaviorDefinitionType.new() as SkeletonBehaviorDefinition
	behavior.melee_profile = load("res://combat/profiles/skeleton_melee.tres") as MeleeAttackProfile
	assert(behavior.melee_profile != null)
	return behavior

func _test_definition_defaults() -> void:
	var behavior := _make_behavior()
	_expect(behavior.validate("test"), "default behavior definition was rejected")
	_expect(is_equal_approx(behavior.roam_speed, 2.4), "roam speed changed")
	_expect(is_equal_approx(behavior.sprint_speed, 5.5), "sprint speed changed")
	_expect(is_equal_approx(behavior.gravity, 30.0), "gravity changed")
	_expect(is_equal_approx(behavior.jump_velocity, 7.0), "jump velocity changed")
	_expect(is_equal_approx(behavior.detection_range, 30.0), "detection range changed")
	_expect(is_equal_approx(behavior.roam_radius, 30.0), "roam radius changed")
	_expect(is_equal_approx(behavior.ambush_range, 5.0), "ambush range changed")
	_expect(behavior.melee_profile.id == &"skeleton_melee", "melee profile ID changed")
	_expect(is_equal_approx(behavior.melee_profile.duration, 0.55), "attack duration changed")
	_expect(is_equal_approx(behavior.melee_profile.contact_time, 0.28), "attack contact time changed")
	_expect(is_equal_approx(behavior.melee_profile.cooldown, 1.1), "attack cooldown changed")
	_expect(is_equal_approx(behavior.melee_profile.reach, 1.4), "attack reach changed")
	_expect(is_equal_approx(behavior.melee_profile.base_damage, 5.0), "attack base damage changed")
	_expect(is_equal_approx(behavior.roam_goal_seconds, 4.0), "roam goal duration changed")
	_expect(is_equal_approx(behavior.repath_seconds, 0.5), "repath duration changed")
	_expect(is_equal_approx(behavior.cover_retry_seconds, 1.0), "cover retry duration changed")
	_expect(is_equal_approx(behavior.cover_revalidation_seconds, 0.125), "cover revalidation duration changed")
	var configured_behavior := load("res://entities/skeleton/skeleton_behavior.tres") as SkeletonBehaviorDefinition
	_expect(configured_behavior != null and configured_behavior.validate(configured_behavior.resource_path), "configured behavior definition was rejected")
	_expect(is_equal_approx(configured_behavior.sprint_speed, 5.5), "configured sprint speed changed")
	_expect(is_equal_approx(configured_behavior.ambush_range, 5.0), "configured ambush range changed")
	_expect(configured_behavior.melee_profile == behavior.melee_profile, "configured behavior did not use the canonical melee profile")
	_expect(is_equal_approx(configured_behavior.cover_retry_seconds, 1.0), "configured cover retry changed")
	_expect(is_equal_approx(configured_behavior.cover_revalidation_seconds, 0.125), "configured cover revalidation changed")

func _test_deterministic_drifting_roam() -> void:
	var behavior := _make_behavior()
	var origin := Vector3(2.5, 7.0, 3.5)
	var first := SkeletonBrainType.new(behavior, 451)
	var second := SkeletonBrainType.new(behavior, 451)
	var distant_player := origin + Vector3(31.0, 0.0, 0.0)
	first.advance(0.0, origin, distant_player, false)
	second.advance(0.0, origin, distant_player, false)
	_expect(first.state == SkeletonBrainType.State.ROAM, "skeleton did not start roaming")
	_expect(first.get_movement_goal().is_equal_approx(second.get_movement_goal()), "same seed produced different roam goals")
	_expect(is_equal_approx(first.get_movement_goal().y, origin.y), "roam goal changed elevation")
	var first_distance := Vector2(first.get_movement_goal().x - origin.x, first.get_movement_goal().z - origin.z).length()
	_expect(first_distance >= behavior.roam_radius * 0.35 and first_distance <= behavior.roam_radius, "initial roam goal exceeded its configured radius")

	var drift_position := Vector3(102.5, 7.0, -96.5)
	distant_player = drift_position + Vector3(31.0, 0.0, 0.0)
	first.advance(behavior.roam_goal_seconds, drift_position, distant_player, false)
	second.advance(behavior.roam_goal_seconds, drift_position, distant_player, false)
	_expect(first.get_movement_goal().is_equal_approx(second.get_movement_goal()), "drifting roam sequence was not deterministic")
	var drift_distance := Vector2(first.get_movement_goal().x - drift_position.x, first.get_movement_goal().z - drift_position.z).length()
	_expect(drift_distance >= behavior.roam_radius * 0.35 and drift_distance <= behavior.roam_radius, "next roam goal was not centered on the current position")
	_expect(Vector2(first.get_movement_goal().x - origin.x, first.get_movement_goal().z - origin.z).length() > behavior.roam_radius, "roam territory remained anchored to its starting position")

	var rejected_goal := first.get_movement_goal()
	first.reject_movement_goal(drift_position)
	_expect(not first.get_movement_goal().is_equal_approx(rejected_goal), "rejected roam goal was retained")
	var replacement_distance := Vector2(first.get_movement_goal().x - drift_position.x, first.get_movement_goal().z - drift_position.z).length()
	_expect(replacement_distance >= behavior.roam_radius * 0.35 and replacement_distance <= behavior.roam_radius, "replacement roam goal exceeded its configured radius")

func _test_detection_and_initial_occlusion() -> void:
	var behavior := _make_behavior()
	var brain := SkeletonBrainType.new(behavior, 810)
	var self_position := Vector3(4.5, 7.0, -2.5)
	var outside_player := self_position + Vector3(30.01, 100.0, 0.0)
	_expect(not brain.needs_detection_occlusion_check(self_position, outside_player), "outside player requested an occlusion check")
	brain.advance(0.0, self_position, outside_player, true)
	_expect(brain.state == SkeletonBrainType.State.ROAM, "hidden position outside detection range stopped roaming")
	var boundary_player := self_position + Vector3(30.0, 100.0, 0.0)
	_expect(brain.needs_detection_occlusion_check(self_position, boundary_player), "detection boundary did not request one occlusion check")
	brain.advance(0.0, self_position, boundary_player, false)
	_expect(brain.state == SkeletonBrainType.State.SEARCH_COVER, "exposed position at detection boundary did not search for cover")
	_expect(not brain.needs_detection_occlusion_check(self_position, boundary_player), "active cover response kept requesting initial occlusion")
	brain.advance(0.0, self_position, self_position + Vector3(20.0, 100.0, 0.0), true)
	_expect(brain.state == SkeletonBrainType.State.SEARCH_COVER, "vertical separation or stale occlusion changed active cover search")
	brain.advance(0.0, self_position, outside_player, false)
	_expect(brain.state == SkeletonBrainType.State.ROAM, "player leaving detection range did not restore roaming")
	_expect(not brain.needs_cover_search() and not brain.is_cover_search_in_progress(), "leaving detection range retained cover work")

	var hidden_brain := SkeletonBrainType.new(behavior, 811)
	var nearby_player := self_position + Vector3(20.0, 0.0, 0.0)
	_expect(hidden_brain.needs_detection_occlusion_check(self_position, nearby_player), "initial nearby player did not request occlusion")
	hidden_brain.advance(0.0, self_position, nearby_player, true)
	_expect(hidden_brain.state == SkeletonBrainType.State.HIDE, "initially hidden Skeleton did not hide")
	_expect(not hidden_brain.needs_detection_occlusion_check(self_position, nearby_player), "hiding Skeleton requested initial occlusion again")
	_expect(not hidden_brain.is_cover_revalidation_due(), "new hide state requested immediate revalidation")

func _test_search_sprint_and_retry_boundaries() -> void:
	var behavior := _make_behavior()
	var brain := SkeletonBrainType.new(behavior, 928)
	var self_position := Vector3(0.5, 1.0, 0.5)
	var nearby_player := self_position + Vector3(10.0, 0.0, 0.0)
	brain.advance(0.0, self_position, nearby_player, false)
	_expect(brain.needs_cover_search(), "entering cover search did not request executor work")
	brain.record_cover_search_started()
	_expect(not brain.needs_cover_search() and brain.is_cover_search_in_progress(), "started foreground search did not become active")
	brain.record_cover_exhausted()
	_expect(brain.state == SkeletonBrainType.State.SPRINT, "exhausted foreground search did not enter sprint")
	_expect(brain.get_movement_goal().is_equal_approx(nearby_player), "sprint did not start toward the current player")
	_expect(not brain.needs_cover_search() and not brain.is_cover_search_in_progress(), "sprint retried cover immediately")

	var moving_player := self_position + Vector3(8.0, 0.0, 6.0)
	brain.advance(0.0, self_position, moving_player, false)
	_expect(brain.get_movement_goal().is_equal_approx(moving_player), "sprint goal did not track the moving player")
	brain.advance(behavior.cover_retry_seconds - 0.001, self_position, moving_player, false)
	_expect(not brain.needs_cover_search(), "cover retry became due before one second")
	brain.advance(0.001, self_position, moving_player, false)
	_expect(brain.needs_cover_search(), "cover retry was not due at exactly one second")
	brain.record_cover_search_started()
	_expect(brain.state == SkeletonBrainType.State.SPRINT and brain.is_cover_search_in_progress(), "background search did not run while sprinting")
	var later_player := self_position + Vector3(-7.0, 0.0, 3.0)
	brain.advance(behavior.cover_retry_seconds * 2.0, self_position, later_player, false)
	_expect(brain.is_cover_search_in_progress() and not brain.needs_cover_search(), "active background search scheduled overlapping work")
	_expect(brain.get_movement_goal().is_equal_approx(later_player), "active background search stopped sprint tracking")
	brain.record_cover_exhausted()
	brain.advance(behavior.cover_retry_seconds * 0.5, self_position, later_player, false)
	_expect(not brain.needs_cover_search(), "re-exhausted search did not reset retry cadence")
	brain.advance(behavior.cover_retry_seconds * 0.5, self_position, later_player, false)
	_expect(brain.needs_cover_search(), "second retry was not due on its one-second boundary")
	brain.record_cover_search_started()
	var cover_target := self_position + Vector3(3.0, 0.0, 2.0)
	brain.record_cover_found(cover_target)
	_expect(brain.state == SkeletonBrainType.State.MOVE_TO_COVER, "background cover result did not enter movement state")
	_expect(brain.get_movement_goal().is_equal_approx(cover_target), "background cover result did not become movement goal")

	brain.reject_cover_goal()
	brain.record_cover_search_started()
	brain.advance(0.0, self_position, self_position + Vector3(31.0, 0.0, 0.0), false)
	_expect(brain.state == SkeletonBrainType.State.ROAM, "leaving detection range did not cancel active cover search")
	_expect(not brain.needs_cover_search() and not brain.is_cover_search_in_progress(), "cancelled cover search retained executor state")

func _test_cover_revalidation_boundaries() -> void:
	var behavior := _make_behavior()
	var brain := SkeletonBrainType.new(behavior, 1264)
	var self_position := Vector3(0.5, 1.0, 0.5)
	var nearby_player := self_position + Vector3(10.0, 0.0, 0.0)
	var cover_target := self_position + Vector3(3.0, 0.0, 2.0)
	brain.advance(0.0, self_position, nearby_player, false)
	brain.record_cover_search_started()
	brain.record_cover_found(cover_target)
	_expect(not brain.is_cover_revalidation_due(), "new cover movement requested immediate target revalidation")
	brain.advance(behavior.cover_revalidation_seconds - 0.001, self_position, nearby_player, false)
	_expect(not brain.is_cover_revalidation_due(), "cover target revalidation became due early")
	brain.advance(0.001, self_position, nearby_player, false)
	_expect(brain.is_cover_revalidation_due(), "cover target was not due at the revalidation boundary")
	brain.record_cover_revalidated(true)
	_expect(not brain.is_cover_revalidation_due(), "valid target did not reset revalidation cadence")
	brain.advance(behavior.cover_revalidation_seconds, self_position, nearby_player, false)
	_expect(brain.is_cover_revalidation_due(), "reset target cadence did not reach its next boundary")
	brain.record_cover_revalidated(false)
	_expect(brain.state == SkeletonBrainType.State.SEARCH_COVER and brain.needs_cover_search(), "invalid target did not request fresh foreground search")

	brain.record_cover_search_started()
	brain.record_cover_found(cover_target)
	brain.record_cover_arrival(false)
	_expect(brain.state == SkeletonBrainType.State.SEARCH_COVER and brain.needs_cover_search(), "exposed arrival was accepted as cover")
	brain.record_cover_search_started()
	brain.record_cover_found(cover_target)
	brain.record_cover_arrival(true)
	_expect(brain.state == SkeletonBrainType.State.HIDE, "occluded cover arrival did not enter hide state")
	_expect(not brain.is_cover_revalidation_due(), "cover arrival requested immediate current-position revalidation")
	brain.advance(behavior.cover_revalidation_seconds, self_position, nearby_player, false)
	_expect(brain.is_cover_revalidation_due(), "hidden position was not due at the revalidation boundary")
	brain.record_cover_revalidated(true)
	brain.advance(behavior.cover_revalidation_seconds - 0.001, self_position, nearby_player, false)
	_expect(not brain.is_cover_revalidation_due(), "valid hidden position became due early")
	brain.advance(0.001, self_position, nearby_player, false)
	_expect(brain.is_cover_revalidation_due(), "valid hidden position missed its next boundary")
	brain.record_cover_revalidated(false)
	_expect(brain.state == SkeletonBrainType.State.SEARCH_COVER and brain.needs_cover_search(), "exposed hidden position did not request foreground search")

func _test_ambush_boundary_and_cover_override() -> void:
	var behavior := _make_behavior()
	var self_position := Vector3(0.5, 1.0, 0.5)
	var outside_player := self_position + Vector3(behavior.ambush_range + 0.001, 80.0, 0.0)
	var boundary_player := self_position + Vector3(3.0, 80.0, 4.0)
	var hidden_brain := SkeletonBrainType.new(behavior, 1511)
	_expect(hidden_brain.needs_detection_occlusion_check(self_position, outside_player), "player beyond the ambush range did not request initial occlusion")
	hidden_brain.advance(0.0, self_position, outside_player, true)
	_expect(hidden_brain.state == SkeletonBrainType.State.HIDE, "hidden Skeleton beyond the ambush range did not remain in cover")
	hidden_brain.advance(0.0, self_position, boundary_player, true)
	_expect(hidden_brain.state == SkeletonBrainType.State.SPRINT, "hidden Skeleton did not sprint at the exact ambush boundary")
	_expect(hidden_brain.get_movement_goal().is_equal_approx(boundary_player), "ambush sprint did not target the current player")
	_expect(not hidden_brain.needs_cover_search() and not hidden_brain.is_cover_search_in_progress(), "ambush sprint retained hidden-position cover work")

	var exposed_brain := SkeletonBrainType.new(behavior, 1512)
	_expect(not exposed_brain.needs_detection_occlusion_check(self_position, boundary_player), "exact ambush boundary requested an unnecessary occlusion check")
	exposed_brain.advance(0.0, self_position, outside_player, false)
	_expect(exposed_brain.state == SkeletonBrainType.State.SEARCH_COVER and exposed_brain.needs_cover_search(), "player beyond the ambush range did not start cover search")
	exposed_brain.advance(0.0, self_position, boundary_player, false)
	_expect(exposed_brain.state == SkeletonBrainType.State.SPRINT, "exact ambush boundary did not override active cover search")
	_expect(not exposed_brain.needs_cover_search() and not exposed_brain.is_cover_search_in_progress(), "ambush override retained stale search work")

	var initial_brain := SkeletonBrainType.new(behavior, 1513)
	initial_brain.advance(0.0, self_position, boundary_player, true)
	_expect(initial_brain.state == SkeletonBrainType.State.SPRINT, "initially hidden Skeleton did not sprint at the exact ambush boundary")

func _test_post_attack_cover_retreat() -> void:
	var behavior := _make_behavior()
	var profile := behavior.melee_profile
	var self_position := Vector3(0.5, 1.0, 0.5)
	var player_position := self_position + Vector3(profile.reach, 0.0, 0.0)
	var cover_target := self_position + Vector3(3.0, 0.0, 2.0)
	var brain := SkeletonBrainType.new(behavior, 1521)
	brain.advance(0.0, self_position, player_position, false)
	_expect(brain.state == SkeletonBrainType.State.ATTACK and brain.consume_attack_started(), "post-cover setup did not begin an attack")
	brain.advance(profile.duration, self_position, player_position, false)
	_expect(brain.state == SkeletonBrainType.State.ATTACK, "completed attack did not retain its state for the completion tick")
	brain.advance(0.0, self_position, player_position, false)
	_expect(brain.state == SkeletonBrainType.State.SEARCH_COVER and brain.needs_cover_search(), "completed attack did not require cover inside the ambush range")
	brain.record_cover_search_started()
	brain.record_cover_found(cover_target)
	brain.advance(0.0, self_position, player_position, false)
	_expect(brain.state == SkeletonBrainType.State.MOVE_TO_COVER, "post-attack retreat attacked before reaching cover")
	brain.reject_cover_goal()
	_expect(brain.state == SkeletonBrainType.State.SEARCH_COVER and brain.needs_cover_search(), "unreachable post-attack cover cleared the retreat")
	brain.record_cover_search_started()
	brain.record_cover_found(cover_target)
	brain.record_cover_arrival(false)
	_expect(brain.state == SkeletonBrainType.State.SEARCH_COVER and brain.needs_cover_search(), "exposed post-attack arrival cleared the retreat")
	brain.record_cover_search_started()
	brain.record_cover_found(cover_target)
	brain.record_cover_arrival(true)
	_expect(brain.state == SkeletonBrainType.State.HIDE, "hidden post-attack arrival did not finish the retreat")
	brain.advance(0.0, self_position, player_position, true)
	_expect(brain.state == SkeletonBrainType.State.SPRINT, "completed cover retreat did not resume a close ambush")
	_expect(not brain.needs_cover_search() and not brain.is_cover_search_in_progress(), "completed cover retreat retained search work")

	var leaving_brain := SkeletonBrainType.new(behavior, 1522)
	leaving_brain.advance(0.0, self_position, player_position, false)
	leaving_brain.consume_attack_started()
	leaving_brain.advance(profile.duration, self_position, player_position, false)
	leaving_brain.advance(0.0, self_position, player_position, false)
	leaving_brain.record_cover_search_started()
	var outside_player := self_position + Vector3(behavior.detection_range + 0.001, 0.0, 0.0)
	leaving_brain.advance(0.0, self_position, outside_player, false)
	_expect(leaving_brain.state == SkeletonBrainType.State.ROAM, "player leaving detection did not cancel the post-attack retreat")
	_expect(not leaving_brain.needs_cover_search() and not leaving_brain.is_cover_search_in_progress(), "leaving detection retained post-attack cover work")
	var boundary_player := self_position + Vector3(behavior.ambush_range, 0.0, 0.0)
	leaving_brain.advance(0.0, self_position, boundary_player, false)
	_expect(leaving_brain.state == SkeletonBrainType.State.SPRINT, "cleared retreat blocked the next ambush")

func _test_attack_timing_no_cover_and_cooldown() -> void:
	var behavior := _make_behavior()
	var profile := behavior.melee_profile
	var brain := SkeletonBrainType.new(behavior, 1541)
	var self_position := Vector3(0.5, 1.0, 0.5)
	var player_position := self_position + Vector3(profile.reach, 0.0, 0.0)
	brain.advance(0.0, self_position, player_position, false)
	_expect(brain.state == SkeletonBrainType.State.ATTACK, "Skeleton did not attack at melee reach")
	_expect(brain.consume_attack_started(), "new Skeleton attack did not report its start")
	_expect(not brain.consume_attack_started(), "Skeleton attack start was consumed more than once")
	_expect(not brain.needs_cover_search() and not brain.is_cover_search_in_progress(), "Skeleton attack retained cover work")

	var moved_player := player_position + Vector3(8.0, 0.0, 3.0)
	brain.advance(profile.duration - 0.01, self_position, moved_player, false)
	_expect(brain.state == SkeletonBrainType.State.ATTACK, "Skeleton attack ended before its duration")
	_expect(not brain.consume_attack_started(), "active Skeleton attack reported another start")
	brain.advance(0.01, self_position, moved_player, false)
	_expect(brain.state == SkeletonBrainType.State.ATTACK, "Skeleton attack state was not retained on its completion tick")
	brain.advance(0.0, self_position, player_position, false)
	_expect(brain.state == SkeletonBrainType.State.SEARCH_COVER and brain.needs_cover_search(), "completed attack skipped its no-cover search")
	brain.record_cover_search_started()
	brain.record_cover_exhausted()
	_expect(brain.state == SkeletonBrainType.State.SPRINT, "exhausted post-attack search did not resume sprinting")
	_expect(not brain.needs_cover_search() and not brain.is_cover_search_in_progress(), "exhausted post-attack search retained cover work")
	brain.advance(profile.cooldown - profile.duration - 0.001, self_position, player_position, false)
	_expect(brain.state == SkeletonBrainType.State.SPRINT, "Skeleton repeated its attack before the cooldown boundary")
	_expect(not brain.needs_cover_search(), "close no-cover fallback scheduled another search before attacking")
	brain.advance(0.001, self_position, player_position, false)
	_expect(brain.state == SkeletonBrainType.State.ATTACK, "Skeleton attack did not restart at its cooldown boundary")
	_expect(brain.consume_attack_started(), "restarted Skeleton attack did not report its start")

func _run() -> void:
	_test_definition_defaults()
	_test_deterministic_drifting_roam()
	_test_detection_and_initial_occlusion()
	_test_search_sprint_and_retry_boundaries()
	_test_cover_revalidation_boundaries()
	_test_ambush_boundary_and_cover_override()
	_test_post_attack_cover_retreat()
	_test_attack_timing_no_cover_and_cooldown()
	if _failures == 0:
		print("SKELETON_BRAIN PASS")
		quit(0)
	else:
		print("SKELETON_BRAIN FAIL failures=%d" % _failures)
		quit(1)
