extends Resource
class_name BlockyHumanoidAnimationProfile

@export_range(0.05, 4.0, 0.001) var walk_cycle_seconds: float = 0.65
@export var walk_bob_height: float = 0.075
@export var walk_leg_travel: float = 0.45
@export var walk_leg_lift: float = 0.18
@export var walk_leg_reach_degrees: float = 30.0
@export var walk_leg_push_degrees: float = 30.0
@export var walk_leg_compression: float = 0.07
@export var walk_limb_stretch: float = 0.035
@export var walk_rhythm_shape: float = 0.10
@export var walk_voxel_squash: float = 0.045
@export var walk_voxel_stretch: float = 0.015
@export_range(0.05, 4.0, 0.001) var sprint_cycle_seconds: float = 0.46
@export var sprint_bob_height: float = 0.14
@export var sprint_leg_travel: float = 0.50
@export var sprint_leg_lift: float = 0.40
@export var sprint_leg_reach_degrees: float = 24.0
@export var sprint_leg_push_degrees: float = 40.0
@export var sprint_leg_compression: float = 0.13
@export var sprint_lean_degrees: float = 8.0
@export var sprint_limb_stretch: float = 0.08
@export var sprint_rhythm_shape: float = 0.01
@export var sprint_voxel_squash: float = 0.075
@export var sprint_voxel_stretch: float = 0.025
@export_range(0.02, 0.12) var gait_contact_hold: float = 0.02
@export_range(0.15, 0.30) var gait_down_pose: float = 0.22
@export_range(0.38, 0.55) var gait_push_pose: float = 0.48
@export_range(0.62, 0.82) var gait_passing_pose: float = 0.72
@export var leg_follow_through_degrees: float = 9.0
@export var locomotion_twist_degrees: float = 3.5
@export var locomotion_sway_degrees: float = 2.5
@export var sprint_arm_swing_degrees: float = 68.0
@export var walk_arm_swing_degrees: float = 46.0
@export var secondary_motion_lag: float = 0.32
@export var acceleration_overshoot_degrees: float = 9.0
@export var braking_overshoot_degrees: float = 14.0
@export var inertia_recovery: float = 7.5
@export var jump_anticipation_depth: float = 0.09
@export var jump_anticipation_squash: float = 0.14
@export var jump_anticipation_widen: float = 0.07
@export var idle_bob_height: float = 0.012
@export_range(0.05, 10.0, 0.001) var idle_cycle_seconds: float = 2.4
@export var idle_torso_pitch_degrees: float = 1.0
@export var idle_torso_sway_degrees: float = 1.5
@export var idle_arm_swing_degrees: float = 1.5
@export var body_lean_degrees: float = 8.0
@export var turn_lean_degrees: float = 8.0
@export var motion_response: float = 11.0
@export var head_response: float = 10.0
@export var head_yaw_limit_degrees: float = 55.0
@export var head_up_limit_degrees: float = 30.0
@export var head_down_limit_degrees: float = 25.0
@export var idle_head_degrees: float = 3.0
@export_range(0.05, 2.0, 0.001) var landing_seconds: float = 0.28
@export_range(0.0, 1.0, 0.001) var landing_hold_seconds: float = 0.055
@export var landing_squash: float = 0.20
@export var landing_widen: float = 0.10
@export var landing_rebound_stretch: float = 0.09
@export var jump_stretch: float = 0.10
@export var jump_torso_pitch_degrees: float = 6.0
@export var jump_arm_pitch_degrees: float = 18.0
@export var jump_arm_spread_degrees: float = 5.0
@export var jump_leg_split_degrees: float = 15.0
@export var fall_torso_pitch_degrees: float = 6.0
@export var fall_arm_pitch_degrees: float = -13.0
@export var fall_arm_spread_degrees: float = 13.0
@export var fall_leg_split_degrees: float = 12.0
@export var landing_torso_pitch_degrees: float = 10.0
@export var landing_arm_pitch_degrees: float = 12.0
@export var landing_leg_pitch_degrees: float = -20.0
@export_range(0.05, 2.0, 0.001) var mine_cycle_seconds: float = 0.35
@export_range(0.05, 2.0, 0.001) var place_seconds: float = 0.18
@export_range(0.0, 180.0, 1.0) var attack_windup_degrees: float = 52.0
@export_range(1.0, 180.0, 1.0) var attack_follow_through_degrees: float = 76.0
@export_range(-180.0, 180.0, 1.0) var attack_right_arm_pitch_degrees: float = -120.0
@export_range(0.0, 90.0, 1.0) var attack_body_lean_degrees: float = 0.0
@export_range(0.0, 90.0, 1.0) var attack_body_twist_degrees: float = 60.0
@export_range(0.0, 90.0, 1.0) var attack_leg_brace_degrees: float = 0.0
@export_range(0.0, 0.5, 0.001) var attack_crouch_depth: float = 0.0
